#
# OpenAPI Petstore
# 
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech
#

import jester
import json
import logging

import config

# APIs
import apis/api_pet
import apis/api_store
import apis/api_user


let logger = newConsoleLogger()
addHandler(logger)


proc main() =
  var jester = initJester(settings = newSettings(
      port = config.port,
      staticDir = config.staticDir,
      appName = config.appName,
      bindAddr = config.bindAddr,
      reusePort = config.reusePort
     )
  )

  jester.register(api_pet.router)
  jester.register(api_store.router)
  jester.register(api_user.router)

  jester.serve()

when isMainModule:
  main()