#
# OpenAPI Petstore
# 
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech
#

import htmlgen
import jester
import logging

import ../models/model_api_response
import ../models/model_pet


router api_pet:
  post "/pet":
    # TODO: POST /pet needs to be implemented
    warn("POST /pet is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  delete "/pet/@petId":
    # TODO: DELETE /pet/@petId needs to be implemented
    warn("DELETE /pet/@petId is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  get "/pet/findByStatus":
    # TODO: GET /pet/findByStatus needs to be implemented
    warn("GET /pet/findByStatus is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  get "/pet/findByTags":
    # TODO: GET /pet/findByTags needs to be implemented
    warn("GET /pet/findByTags is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  get "/pet/@petId":
    # TODO: GET /pet/@petId needs to be implemented
    warn("GET /pet/@petId is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  put "/pet":
    # TODO: PUT /pet needs to be implemented
    warn("PUT /pet is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  post "/pet/@petId":
    # TODO: POST /pet/@petId needs to be implemented
    warn("POST /pet/@petId is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  post "/pet/@petId/uploadImage":
    # TODO: POST /pet/@petId/uploadImage needs to be implemented
    warn("POST /pet/@petId/uploadImage is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))


const router* = api_pet