#
# OpenAPI Petstore
# 
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech
#

import htmlgen
import jester
import logging

import ../models/model_user


router api_user:
  post "/user":
    # TODO: POST /user needs to be implemented
    warn("POST /user is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  post "/user/createWithArray":
    # TODO: POST /user/createWithArray needs to be implemented
    warn("POST /user/createWithArray is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  post "/user/createWithList":
    # TODO: POST /user/createWithList needs to be implemented
    warn("POST /user/createWithList is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  delete "/user/@username":
    # TODO: DELETE /user/@username needs to be implemented
    warn("DELETE /user/@username is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  get "/user/@username":
    # TODO: GET /user/@username needs to be implemented
    warn("GET /user/@username is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  get "/user/login":
    # TODO: GET /user/login needs to be implemented
    warn("GET /user/login is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  get "/user/logout":
    # TODO: GET /user/logout needs to be implemented
    warn("GET /user/logout is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  put "/user/@username":
    # TODO: PUT /user/@username needs to be implemented
    warn("PUT /user/@username is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))


const router* = api_user