#
# OpenAPI Petstore
# 
# This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech
#

import htmlgen
import jester
import logging

import ../models/model_order


router api_store:
  delete "/store/order/@orderId":
    # TODO: DELETE /store/order/@orderId needs to be implemented
    warn("DELETE /store/order/@orderId is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  get "/store/inventory":
    # TODO: GET /store/inventory needs to be implemented
    warn("GET /store/inventory is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  get "/store/order/@orderId":
    # TODO: GET /store/order/@orderId needs to be implemented
    warn("GET /store/order/@orderId is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))

  post "/store/order":
    # TODO: POST /store/order needs to be implemented
    warn("POST /store/order is not implemented")
    resp(Http501, "<!DOCTYPE html>" & html(body("Not Implemented")))


const router* = api_store